### ISSUE TITLE
Coverage report is incomplete since moving the source to a sub-folder

### ISSUE THREAD

**Issue by MrTimscampi** [jellyfin/jellyfin-vue#1022]
For some reason, coverage reporting is incomplete. It only takes coverage for a limited part of the source, leading to erroneous numbers and reports from Codecov.

Ideally, coverage should take all source files into account, not only files with tests.

**Comment by ferferga** [comment]
No longer relevant - all coverage reporting is going to live in SonarCloud from now on.
