### ISSUE TITLE
Vue doesn't load any Jellyfin servers/items on mobile

### ISSUE THREAD

**Issue by Perseusdehond** [jellyfin/jellyfin-vue#1058]
**Describe The Bug**

Vue doesn't load any Jellyfin servers/items on mobile or keeps loading the home page forever with only the welcome message showing.

**Steps To Reproduce**

1. Go to 'https://jellyfin-vue.pages.dev' on **mobile**
2. Use 'https://demo.jellyfin.org/stable' as the server
3. Use 'demo' as username and leave password empty
4. The home page won't load like in the screenshot
PS: You can also use your own server to reproduce this as this also doesn't work.

**Expected Behavior**

Vue should load Jellyfin servers/items on mobile.

**Screenshots**

![Screenshot_20210427-093858_Chrome](https://user-images.githubusercontent.com/42120256/116205674-43120f00-a73e-11eb-8617-d313005af653.jpg)

**System (please complete the following information):**

- Platform: [Android/Mobile]
- Browser: [Chrome, Edge]
- Jellyfin Server: [10.7.x]

**Comment by MrTimscampi** [comment]
This is already fixed by #1036

**Comment by Perseusdehond** [comment]
Ah didn't notice that, but great to hear!
