### ISSUE TITLE
"item detail" page get incomplete data

### ISSUE THREAD

**Issue by s0urcelab** [jellyfin/jellyfin-vue#1059]
**Describe The Bug**

 "item detail" page get incomplete data when redirect from "person" page.

**Steps To Reproduce**

1. Go to 'item' page
2. Click on any 'person'
3. Click any 'item' from this person
4. 'item' page get incomplete data

**Expected Behavior**

should get full item data

**Screenshots**

![image](https://user-images.githubusercontent.com/13177782/116258105-2dafdb80-a764-11eb-84f1-888131eb6336.png)

![image](https://user-images.githubusercontent.com/13177782/116258292-589a2f80-a764-11eb-8116-a917e4051872.png)

![image](https://user-images.githubusercontent.com/13177782/116258401-74053a80-a764-11eb-983f-ad0a3c8cac52.png)

**System (please complete the following information):**

- Platform: Windows 10
- Browser: Chrome 78
- Jellyfin Version: 10.7.2

**Comment by s0urcelab** [comment]
https://github.com/jellyfin/jellyfin-vue/blob/3aa8edc801f6ddb10497d243a8f168b60bd00614/client/pages/item/_itemId/index.vue#L273

when redirect from person page, vue store still holds item data(that is incomplete) in cache, so item page wouldn't send request for fresh data.

**Comment by akkisagiraju** [comment]
@s0urcelab I found out that the line 273 is not the problem. When you click on a person on the item page, the item object (of movie/tv show) is getting overridden with partial data.
