### ISSUE TITLE
Is there a todolist？

### ISSUE THREAD

**Issue by Dec-F** [jellyfin/jellyfin-vue#111]
I want to get involved, but I don't know what needs to be done and which modules are already under development. Hope that there can be a todolist to synchronize this information to help potential developers to participate

**Comment by dkanada** [comment]
If there's a certain page or feature you want, you can open an issue here to claim the feature and explain the planned implementation at the same time.

**Comment by MrTimscampi** [comment]
I can make a meta-issue later today (GMT+2) with a list of things that need work, so people can claim them. We've been doing things as we go until now, but you're right that it's easier to get people involved if we have a list of things to work on.

**Comment by Camc314** [comment]
> I can make a meta-issue later today (GMT+2) with a list of things that need work, so people can claim them. We've been doing things as we go until now, but you're right that it's easier to get people involved if we have a list of things to work on.

This sounds like a good idea.


Music is something that needs a lot of work. Things like list view (jellyfin-web) need to be implemented in jf-vue. Similarly, nowplaying/music needs to be implemented.

As for TV Shows/Films, things like:
 - Identifying items
 - Image Editors

Both need to be done

**Comment by MrTimscampi** [comment]
Update: The to-do list is in progress. It takes quite a bit of time to figure out all the features from jf-web we need to mirror or find an alternative for, as well as dividing them into sensible parts.

**Comment by MrTimscampi** [comment]
#115 is up and provides an hopefully exhaustive list of what I'm looking for before declaring this production-ready (The goal being feature parity with the current web client).

I'll close this one, since the list is up. Don't hesitate to ask for more info on that issue or by opening one you'd like to work on.
