### ISSUE TITLE
Add a proper nuxt-auth schema for authentication

### ISSUE THREAD

**Issue by MrTimscampi** [jellyfin/jellyfin-vue#136]

**Comment by Stampede10343** [comment]
Not sure if its related but I'm noticing if you hang on the home page for a few minutes then try navigating into a library you get soft logged out, but manually putting in the home url and loading it gets you logged back in. I don't see any 401's or anything that would indicate a session going stale.

**Comment by MrTimscampi** [comment]
Yep, it's related :)

The auth plugin sort of expects the token to be refreshed. I'm actually thinking about ditching nuxt-auth entirely and building something entirely custom.

**Comment by ferferga** [comment]
@MrTimscampi Shall we close this after #263 ?

**Comment by MrTimscampi** [comment]
Indeed, I thought I had closed this, somehow.
