### ISSUE TITLE
"Soft" back arrow can be clicked when hidden and also gets you out of JF Vue

### ISSUE THREAD

**Issue by ThibaultNocchi** [jellyfin/jellyfin-vue#1365]
The back arrow on the top bar (the Vue one, not the browser one) is hidden on the homepage but can be clicked.

Also, if you click on it it's a simple backward navigation in the history, returning you to wherever you were, be it Vue or not.

**Comment by MrTimscampi** [comment]
That would be because the `hide` directive added by @ferferga uses `el.style.opacity = '0'`, which doesn't disable any of the elements or their events.
