### ISSUE TITLE
Add cards for the visible users on the login screen

### ISSUE THREAD

**Issue by MrTimscampi** [jellyfin/jellyfin-vue#138]

**Comment by quaz4** [comment]
Happy to pick this one up, is there anything extra I should be aware of with this issue?

**Comment by MrTimscampi** [comment]
Hi @quaz4.

You'll need a Jellyfin server (even an empty one) to work on this, as our demo server doesn't have visible users.
The goal of this is to essentially replicate the behavior of the current web client (https://github.com/jellyfin/jellyfin-web):

* When showing the login page, if there are visible users on the server, show a card for each of them (otherwise, show the login form)
* Upon clicking on one of the cards, show the login screen with the username pre-filled

You'll need to query `/Users/Public` using the OpenAPI client in the `~/api` directory. The API client is fully typed, but if you need some easy to read documentation, it should be available here: https://demo.jellyfin.org/unstable/api-docs/redoc/index.html#operation/GetPublicUsers

To make a user public on your server, go to the User menu (top right) > Dashboard > Users > Your user, and untick "Hide this user from login screens".
