### ISSUE TITLE
Add server manifest checking

### ISSUE THREAD

**Issue by MrTimscampi** [jellyfin/jellyfin-vue#140]
When connecting to a server (Either automatically via #139 or with user interaction), we need to check the server for a manifest, in order to confirm that it is a valid Jellyfin server.

This should be done when validating a server on the server selection page and when loading the client.

**Comment by phyzical** [comment]
Hey ill take this one too 👍 

just to confirm was there a specific endpoint we wanted to verify against? 

i was thinking /System/Ping or /System/Info

**Comment by MrTimscampi** [comment]
Hi @phyzical ! Thanks for the interest and sorry for the late response :smiley: 

Unfortunately, I recently took care of this one due to a new endpoint we're adding to the API, which is needed to fix the login issues we've been having. So it's pretty much done, sorry (We're checking the version on login, which requires the manifest, so that's enough to close this).

**Comment by phyzical** [comment]
:D no worries!
