### ISSUE TITLE
Add a skeleton loader for home screen sections

### ISSUE THREAD

**Issue by MrTimscampi** [jellyfin/jellyfin-vue#142]

**Comment by IDTitanium** [comment]
Hi, @MrTimscampi some quick question please. Is this a design task? also, does this app use any material design system?

**Comment by MrTimscampi** [comment]
Hi @IDTitanium!

This issue is to track the implementation of it and discuss details before opening a PR, for anyone willing to work on it.

It was previously part of #115 , but it makes more sense to split them and use a Project, so this is what I'm doing currently :smile: 

This app uses Vuetify for components, so you have [some skeleton loaders](https://vuetifyjs.com/en/components/skeleton-loaders/) available already.

The gist of this task would be to add placeholder components using the Vuetify loaders while data is being fetched from the server.

Relevant code is [here](https://github.com/jellyfin/jellyfin-vue/blob/master/pages/index.vue#L3-L8) and [here](https://github.com/jellyfin/jellyfin-vue/blob/master/components/HomeSection.vue).

Do note that you'll need a Jellyfin server to work on this. We have a public one available at `https://demo.jellyfin.org/unstable/`, if needed.

**Comment by IDTitanium** [comment]
Ok great. I will look into this task.

**Comment by Camc314** [comment]
Completed by #328
