### ISSUE TITLE
Enable modern bundle

### ISSUE THREAD

**Issue by ThibaultNocchi** [jellyfin/jellyfin-vue#1516]
### Description of the bug

After #1515, modern bundle has been disabled to make it work with the transpiled jf-client-axios dependency.

We should investigate that further to make it work. Either fix the dependency or our build methods.

**Comment by ferferga** [comment]
Seems Nuxt 3 will be modern by default: https://github.com/nuxt/nuxt.js/issues/4552#issuecomment-761786540

Which makes sense, since Vue 3 won't support old browsers anyway.
We can close this as soon as we move to Nuxt 3 (or we investigate if Nuxt bridge has that covered as well)
