### ISSUE TITLE
fMP4 with AAC playback doesn't work with Shaka 3.2.0

### ISSUE THREAD

**Issue by ThibaultNocchi** [jellyfin/jellyfin-vue#1518]
### Description of the bug

Playing fMP4 files with AAC with Shaka 3.2.0 doesn't work. TS and AAC works, and 3.1.2 works.

Current solution is to disable AAC with fMP4 for now.

### Steps to reproduce

Play a file transcoded to a fMP4 container with AAC audio in it.

### Expected behavior

It shoudl work

### Platform

Linux

### Browser

Firefox

### Jellyfin server version

10.7.7

### Additional context

Waiting for feedbacks from here: https://github.com/google/shaka-player/issues/3691

Maybe it also relates to #1484?

**Comment by nyanmisaka** [comment]
This issue has be fixed in https://github.com/shaka-project/shaka-player/pull/4241.
fMP4 playback can be enabled again with shaka 4.1.0.
