### ISSUE TITLE
Going 'back' at 'fullscreen/playback' is repeated when starting any other playback after

### ISSUE THREAD

**Issue by Larvitar** [jellyfin/jellyfin-vue#1544]
### Description of the bug

After exiting fullscreen music player 'back' action will be performed after clicking any other `play` button indefinitelly. Only clicking a library link (possibly some other too) allows to break out of this loop.

### Steps to reproduce

1. Go deeper into your music library (Home -> Music -> Album)
2. Start playback of any music in here (`Play` button).
3. Open fulscreen player (`fullscreen/playback`).
4. Exit fullscreen player either by using browser back button or Vue 'soft' back arrow.
    If you started at 'Album', you'll be at 'Music' view right now.
5. Start playback of any album. Playback will start, but at the same you'll go 'back' to home screen.
6. Again click `play` on anything here. You'll go back again - only this time back out of JellyfinVue into empty browser card.

### Expected behavior

`Back` should not be repeated at every action?

### Platform

Linux

### Browser

Chrome

### Jellyfin server version

10.7.7

**Comment by ferferga** [comment]
Fixed in #1593
