### ISSUE TITLE
Music playback volume resetting when starting a new playback instance

### ISSUE THREAD

**Issue by Vodes** [jellyfin/jellyfin-vue#1545]
### Description of the bug

The volume you set in the player keeps resetting to 100 when starting a new playback anywhere.
This does not happen when you go to a different track in the current queue.

### Steps to reproduce

I am using a docker build of the latest master on my server but this also happens on the online demo.
Here's a small gif showing the issue
![](https://vodes.pw/i/Alex/Y9pss8YHJxRKglK.gif)

### Expected behavior

Preserve set volume

### Platform

Linux

### Browser

Firefox

### Jellyfin server version

10.7.6

**Comment by ferferga** [comment]
Why do you think this should be the preferred behaviour?
