### ISSUE TITLE
Video doesn't fill the screen if it's smaller than the screen resolution

### ISSUE THREAD

**Issue by lunananananananana** [jellyfin/jellyfin-vue#1556]
### Description of the bug

When I play a 1080p video on my 1440p monitor, it only fills a 1080p area of the screen. When I resize the window to be smaller than the video, it scales as expected. When I play a 4K video, it also works as expected. 

### Steps to reproduce

Play a video that's smaller than the screen resolution

### Expected behavior

The video should scale up to fill the screen, with letterboxing if it's a different aspect ratio

### Platform

Linux

### Browser

Firefox

### Jellyfin server version

10.7.7

**Comment by ThibaultNocchi** [comment]
That's handled in PR #1554 I submitted like an hour ago :)
