### ISSUE TITLE
Subtitle backdrop oversized

### ISSUE THREAD

**Issue by krutburken** [jellyfin/jellyfin-vue#1557]
### Description of the bug

The black backdrop/background behind subtitles is way too large.

### Steps to reproduce

Start playback, enable subtitles (srt in my case)

### Expected behavior

Either no background at all, or it should match the size of the text being shown.

### Screenshots

![Screenshot 2021-10-21 200411](https://user-images.githubusercontent.com/13684929/138332551-2c57a82b-3f0c-45b9-a067-53da960bb361.png)

### Platform

Windows

### Browser

Firefox

### Jellyfin server version

10.7.7

**Comment by ThibaultNocchi** [comment]
Styling should work in Chromium, but you'll have to wait for [this PR](https://github.com/jellyfin/jellyfin/pull/6777) a new JF version for them work in FF

**Comment by krutburken** [comment]
Very nice :)

**Comment by ThibaultNocchi** [comment]
I just applied some basic styling. But eventually it should all be user customisable :)

**Comment by krutburken** [comment]
Looks good on chromium, but waiting on [6777](https://github.com/jellyfin/jellyfin/pull/6777) since I'm a FF-user. Yep that would be a great addition.
