### ISSUE TITLE
[Enhancement] Ability to predefine a jellyfin server in the docker-compose.yaml

### ISSUE THREAD

**Issue by ma-karai** [jellyfin/jellyfin-vue#1603]
### Description of the bug

It would be great if a predefined jellyfin server could be added via an ENV variable in the docker-compose file. 

### Steps to reproduce

--

### Expected behavior

---

### Platform

Linux

### Browser

Chrome

### Jellyfin server version

10.8.0

**Comment by doc-code-hub** [comment]
I'm thinking of working on it in the next few days...

It seems like a great idea to be able to define a default server address during deployment!

**Comment by ma-karai** [comment]
Awesome news!

**Comment by doc-code-hub** [comment]
One was not enough according to the community :)

For this reason when this PR (#1698) is approved we will have the possibility to specify X servers separated by commas (or even not, of course) :)
