### ISSUE TITLE
Is Cloudflare Pages still active

### ISSUE THREAD

**Issue by MarcelCoding** [jellyfin/jellyfin-vue#1648]
I always used https://jellyfin-vue.pages.dev but in the last commit, I can not find the cloudflare pages build status? Did you disable cloudflare pages? If yes, why? So I did not have to deploy it on my own or do you now manually somewhere else?

**Comment by ThibaultNocchi** [comment]
You're right, the CF instance isn't updated as of now. We're trying to migrate it to the JF CF account but it's a long process and we're busy with other things lately. But it should eventually come back cause it's a useful feature for sure :)

**Comment by MarcelCoding** [comment]
I think this process is completed. The commit in the master branch are containing the link: https://jf-vue.pages.dev
