### ISSUE TITLE
npm install fails with the error: npm ERR! Invalid name: "@jellyfin-vue"

### ISSUE THREAD

**Issue by Seb3thehacker** [jellyfin/jellyfin-vue#1749]
### Description of the bug

npm install fails with the error: 

npm ERR! Invalid name: "@jellyfin-vue"
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/USER/.npm/_logs/2022-04-27T22_53_51_921Z-debug.log

[2022-04-27T22_53_51_921Z-debug.log](https://github.com/jellyfin/jellyfin-vue/files/8578304/2022-04-27T22_53_51_921Z-debug.log)

### Steps to reproduce

git clone https://github.com/jellyfin/jellyfin-vue.git
cd jellyfin-vue
npm install
npm start <--- fails here

### Expected behavior

It should build and run.

### Platform

Linux

### Browser

Firefox

### Jellyfin server version

10.7.6

**Comment by ferferga** [comment]
Check the [prerequisites](https://github.com/jellyfin/jellyfin-vue#dependencies): you're using npm 6 and node 10 (which is ancient and EOL since May 2021)
