### ISSUE TITLE
Kill ffmpeg process immediately after closing the webpage.

### ISSUE THREAD

**Issue by HySand** [jellyfin/jellyfin-vue#1781]
### Description of the bug

I noticed that if the webpage is closed instead of clicking the close ("x") button on the left top of the video to stop it, the ffmpeg process still exists for a long time. However the vanilla client will kill the process at once in same situation.

### Steps to reproduce

Play any video and close the page.

### Expected behavior

Kill ffmpeg process immediately or faster.

### Platform

Linux

### Browser

Edge

### Jellyfin server version

10.8.1

**Comment by ferferga** [comment]
@HySand Can you try now that we have merged the vue 3 changes?

**Comment by ThibaultNocchi** [comment]
I confirm this is still the case.
