### ISSUE TITLE
[ Improvement Request ] Jellyfin Vue Desktop

### ISSUE THREAD

**Issue by AnonymousWebHacker** [jellyfin/jellyfin-vue#1793]
I was reading this number, and it is closed without solving  https://github.com/jellyfin/jellyfin-vue/issues/910

In my case, the videos are h265 and the browsers are not able to play the videos.  A  desktop version is necessary, with an mpv below

**Comment by ferferga** [comment]
Did you check our Tauri builds? 

See artifacts of this run: https://github.com/jellyfin/jellyfin-vue/actions/runs/3029446124

Tauri just gets the client bundled without any special treatment, so probably H265 won't still work, but you can try it in the meantime

**Comment by AnonymousWebHacker** [comment]
wow, I didn't know they were already building for desktop.

I was reviewing and it looks great, a few tweaks, and it's perfect
![Captura desde 2022-09-12 13-54-07](https://user-images.githubusercontent.com/43164089/189733718-be3b2983-031f-43d2-9f70-5e16d7a48c61.png)

maybe it's the wrong place, but I'll leave these improvements

## improvements
left sidebar -- > I could add the option to hide, resize or only show the icons (it takes up space in viewing the indexed content).

Improve video playback with more efficient formats for streams (av1, vp8, vp9, h265 HEVC) (I think it's time to incorporate mpv libraries).

On the Welcome Home screen, there is a slider with the latest content. It's very cool, but it's useless, without some metadata, like about (what the movie or series is about).

Full Screen

If there is a single video, with only 1 internal embedded audio, and with only 1 subtitles (or no subtitles), it is not necessary to pull out a collapsible list with those options.

They should take more advantage of the backdrop and landscape data from the movie or serie

**Comment by bvoo** [comment]
Are there any plans to embed MPV into this akin to [jellyfin-media-player](https://github.com/jellyfin/jellyfin-media-player)?

**Comment by AnonymousWebHacker** [comment]
> Are there any plans to embed MPV into this akin to [jellyfin-media-player](https://github.com/jellyfin/jellyfin-media-player)?

You ask the option to embed mpv to jellyfin-vue or jellyfin-media-player?
Media_player has an mpv below

**Comment by bvoo** [comment]
> 

Into jellyfin-vue

**Comment by ferferga** [comment]
Closing this as there's already a desktop player ready to use and further improvements to it are down the roadmap, but this issue doesn't tackle any of them specifically.

**Comment by AnonymousWebHacker** [comment]
@ferferga Could you publish the builds (deb, exe , ..etc as releases?

**Comment by ferferga** [comment]
> @ferferga Could you publish the builds (deb, exe , ..etc as releases?

We have Docker as of now only, for those to work we would need to make releases, which will only happen when we feel major milestones/features etc are reached.
