### ISSUE TITLE
Scrollbar showing in both directions

### ISSUE THREAD

**Issue by MominRaza** [jellyfin/jellyfin-vue#1794]
### Description of the bug

In filters dropdown scrollbar showing in both directions instead of only Vertical direction.
![image](https://user-images.githubusercontent.com/42776853/190167374-e991c458-d068-4334-9a91-3f6b94433606.png)

### Steps to reproduce

Movies->Filter->Features

### Expected behavior

It should show scrollbar in vertical direction
![image](https://user-images.githubusercontent.com/42776853/190167912-211494c2-70db-44f6-b949-2f639de275bf.png)

### Platform

Windows

### Browser

Chrome

### Jellyfin server version

10.8.4

### Additional context

```text
Can easily fix by replacing
overflow: scroll;
by
overflow: hidden;
overflow-y: auto;
```

**Comment by ferferga** [comment]
Check if this doesn't break anything else and open a PR, as you already have the fix.

Thank you very much!

**Comment by MominRaza** [comment]
I'm not familiar with Vue and this project, but I know css and react
But I will try

**Comment by sfkpmr** [comment]
#1773 Related?
