### ISSUE TITLE
Logos are sometimes ignored from the main page slide content

### ISSUE THREAD

**Issue by Ge082** [jellyfin/jellyfin-vue#1803]
### Description of the bug

Some logos are ignored from the slide content thing on the main page

![Sans titre 36](https://user-images.githubusercontent.com/76789478/200710818-5df79543-2e5f-4042-bdb7-4dff475bec84.png)

![Sans titre 38](https://user-images.githubusercontent.com/76789478/200710771-d49751c2-ce9e-48c2-84d9-04b108c86ab2.png)

Both of these media contains a logo, only one displays it, it's also displayed on Jellyfin's media info page.
Logo size are identical.

### Steps to reproduce

Scrolls between media infos

### Expected behavior

Logos that exists should be displayed on the slider thing

### Platform

Windows

### Browser

Chrome

### Jellyfin server version

10.8

**Comment by TheRedSpy15** [comment]
Do any errors get logged in your browser's console when this happens?

**Comment by ferferga** [comment]
@TheRedSpy15 @Ge082 Hello! Can you please check if #2201 fixes the issue for you? There will always be a deployment link in the PR.

Feedback is much appreciated.

**Comment by TheRedSpy15** [comment]
@ferferga I believe you tagged me by accident

@Ge082
