### ISSUE TITLE
No link back to a series or season from an episode.

### ISSUE THREAD

**Issue by BrianCArnold** [jellyfin/jellyfin-vue#1822]
### Description of the bug

No link back to a series or season from an episode.

### Steps to reproduce

Go to any episode, no link back to a series or season from an episode.

### Expected behavior

Should have a link back to a series or season from an episode.

### Platform

Linux

### Browser

Chrome

### Jellyfin server version

10.8.8

### Additional context

```text
I'm creating a merge request for this
```

**Comment by ferferga** [comment]
Introduced in #2135
