### ISSUE TITLE
--openssl-legacy-provider is not allowed in NODE_OPTIONS

### ISSUE THREAD

**Issue by Coll147** [jellyfin/jellyfin-vue#1831]
### Description of the bug

root@pimedia:/var/www/jellyfin-vue# NODE_OPTIONS=--openssl-legacy-provider npm start
node: --openssl-legacy-provider is not allowed in NODE_OPTIONS

### Steps to reproduce

Put the command NODE_OPTIONS=--openssl-legacy-provider npm start

### Expected behavior

idk

### Logs

```text
root@pimedia:/var/www/jellyfin-vue# NODE_OPTIONS=--openssl-legacy-provider npm start
node: --openssl-legacy-provider is not allowed in NODE_OPTIONS
root@pimedia:/var/www/jellyfin-vue# NODE_OPTIONS=--openssl-legacy-provider npm start
node: --openssl-legacy-provider is not allowed in NODE_OPTIONS
root@pimedia:/var/www/jellyfin-vue#
```

### Platform

Linux

### Browser

Chrome

### Jellyfin server version

10.8.8

**Comment by ferferga** [comment]
Which node version do you have?

**Comment by Coll147** [comment]
v16.18.1

**Comment by ferferga** [comment]
What if you remove the environment command and just do npm start?

By the way, if you don't want to do development, you're better off using the Docker container or the hosted demo (even with your own server).

**Comment by Coll147** [comment]
Well, when I try to access with domain and ssl I get the following error.

ERR_SSL_VERSION_OR_CIPHER_MISMATCH
```
server {
    listen 80;
    server_name domain.lol;
    return 301 https://$host$request_uri;
}
server {
     listen 443 ssl http2;
     listen [::]:443 ssl http2;
    server_name domain.lol;
    ssl_certificate /etc/nginx/ssl/domain.lol/cert.pem;
    ssl_certificate_key /etc/nginx/ssl/domain.lol/privkey.pem;
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";
    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Protocol $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_buffering off;
    }
    location /socket {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Protocol $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
    }
}
```
Here I attach my jellyfinvue configuration (I use the same one for normal jellyfin) in case it is an error of this

**Comment by Coll147** [comment]
Well, when I try to access with domain and ssl I get the following error.

ERR_SSL_VERSION_OR_CIPHER_MISMATCH
```
server {
    listen 80;
    server_name domain.lol;
    return 301 https://$host$request_uri;
}
server {
     listen 443 ssl http2;
     listen [::]:443 ssl http2;
    server_name domain.lol;
    ssl_certificate /etc/nginx/ssl/domain.lol/cert.pem;
    ssl_certificate_key /etc/nginx/ssl/domain.lol/privkey.pem;
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";
    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Protocol $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_buffering off;
    }
    location /socket {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Protocol $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
    }
}
```
Here I attach my jellyfinvue configuration (I use the same one for normal jellyfin) in case it is an error of this

**Comment by Coll147** [comment]
*obviously the domain.lol I have put them to hide my domain.

**Comment by Coll147** [comment]
*obviously the domain.lol I have put them to hide my domain.

**Comment by ferferga** [comment]
*Switching to Spanish as this has nothing to do with Jellyfin Vue but I want to still help the user :)*

Lo que me has mandando es la configuración de nginx, que no tiene nada que ver con el cliente. El error ese tampoco tiene nada que ver con el cliente, es exclusivamente de configuración del servidor web. 

Qué es lo que quieres hacer exactamente? Por qué quieres compilar el cliente?

**Comment by Coll147** [comment]
A ver, yo lo que quiero es poner mi propia estancia de jellyfinvue con dominio y ssl pero me da ese error con el ssl

**Comment by ferferga** [comment]
Si no te importa tener que actualizar manualmente, lo mejor es que sustituyas el cliente web (fíjate con top o htop en la ubicación del cliente, al iniciarse el servicio se le pasa como argumento al ejecutable) y que de vez en cuando descargues los artefactos de los commits que se publiquen: https://github.com/jellyfin/jellyfin-vue/actions/workflows/unstable.yml

Si quieres tener ambos a la vez, tienes que crear un nuevo bloque location para él o alojarlo en un subdominio (hay miles de tutoriales en Internet)

Tener el cliente de esta manera no va a hacer que la pantalla de añadir servidor deje de salir.

**Comment by martadinata666** [comment]
`ERR_SSL_VERSION_OR_CIPHER_MISMATCH` this error likely related to openssl version differences on the host. You can kindly check which version is it. I encountered this on different application, in simple terms `the cert generated with openssl3 and the client with openssl1 cant read it`, at least that is my case.

**Comment by Coll147** [comment]
@martadinata666 I have jellyfin server and jellyfin vue with different subdomains and same configuration (including open ssl version).

**Comment by Coll147** [comment]
@martadinata666 I have jellyfin server and jellyfin vue with different subdomains and same configuration (including open ssl version).

**Comment by Coll147** [comment]
I already found the error because it did not load and it is that there was an error related to the certificate and it is that it did not cover my subdomain.
