### ISSUE TITLE
Docker overview

### ISSUE THREAD

**Issue by VampiricAlien** [jellyfin/jellyfin-vue#1847]
### Description of the bug

Not a bug!

Can you please add an overview to the docker hub page or a link to here for anyone who find the docker page from other places.

### Steps to reproduce

N/A

### Expected behavior

N/A

### Platform

Linux

### Browser

Firefox

### Jellyfin server version

10.8.0

### Additional context

```text
Can not wait to try this out! thanks for the docker image!
```

**Comment by ThibaultNocchi** [comment]
It is done. :)
