### ISSUE TITLE
Reloading the page removes the port from the URL

### ISSUE THREAD

**Issue by FarisR99** [jellyfin/jellyfin-vue#1873]
### Description of the bug

When I navigate to the Settings page and reload the browser, the port gets removed from the URL and I end up on my Apache server's page running on port 80.

This does not seem to happen when I'm on any page other than a page under `/settings/`.

This also happens if I directly enter a URL under settings, e.g. `http://<ip>:<port>/settings`

### Steps to reproduce

1. Navigate to the settings page
2. Reload the browser, or copy the URL and paste it in a new tab
3. You should see the port removed

### Expected behavior

Port is still part of the URL.

### Platform

Linux

### Browser

Chrome

### Jellyfin server version

10.8.9

### Additional context

```text
Running in a Docker container with port 8097 mapped to port 80.
```

**Comment by ThibaultNocchi** [comment]
Hello, thanks for the issue!

Indeed, I've confirmed it with the latest `unstable` Docker image.
I'll wait for this, cause we are currently migrating the client to Vue 3, so maybe it'll be a non-issue when it's done. :)

**Comment by ferferga** [comment]
@FarisR99 Please try now and report back

**Comment by FarisR99** [comment]
@ferferga Works perfectly thanks
