### ISSUE TITLE
[vite] Icons not visible on iOS

### ISSUE THREAD

**Issue by ThibaultNocchi** [jellyfin/jellyfin-vue#1902]
### Description of the bug

Since 85eb2e0ec412b45e809af85a6a0dc660c8241ca8, having set up the scale to `0` makes the icons invisible on iOS. As this was done to fix overflows problems, we need to discuss how to fix it.

### Steps to reproduce

Run a `vite` branch on an iPhone.

### Expected behavior

See the icons

### Platform

iOS

### Browser

Safari

### Jellyfin server version

10.8.9

**Comment by ferferga** [comment]
Solved in #1903
