### ISSUE TITLE
Scaling issue (i.e. 1440p)

### ISSUE THREAD

**Issue by TimGels** [jellyfin/jellyfin-vue#1924]
### Description of the bug

There are scaling issue with some components on screens resolutions other than 1920p x 1080p. While it is not a critical issue, some UI components look a bit weird on different screen resolutions. As an example I provided a couple of screenshots in the screenshot section of this issue.

### Steps to reproduce

Use a 1440p screen resolution. This can easily be emulated in browsers.

### Expected behavior

Nice and 🤌 looking scaling on other screen resolutions than 1920p x 1080p.

### Logs

```text
N/A
```

## 1440p show thumbnails
![afbeelding](https://user-images.githubusercontent.com/43609220/229859488-fe4eb88b-de5f-4443-b9e0-14a9c1ea86cf.png)

## 1080p show thumnails
![afbeelding](https://user-images.githubusercontent.com/43609220/229859783-d0bdcfc2-16da-4456-8c53-a40fa3063c96.png)

## 1440p home screen
![afbeelding](https://user-images.githubusercontent.com/43609220/229860425-754adc05-bc37-40ca-84b0-a160aeead420.png)

## 1080p home screen
![afbeelding](https://user-images.githubusercontent.com/43609220/229860532-73a3bb91-6bc1-4a8a-bf24-f18dfe7d76a4.png)

### Platform

Windows

### Browser

Firefox

### Jellyfin server version

10.8.9

### Additional context

```text
N/A
```

**Comment by TimGels** [comment]
> This is something that we are aware of, we mainly developed and tested on 1080p. We only aimed for something usable on mobile and >1080p.

I know this is something that is already known. This issue is more meant to keep track of it : ) Great work on Vue 3

**Comment by ThibaultNocchi** [comment]
No problem, thanks! Had a rough day, and with the recent launch it's hard to see who's new or not :)
