### ISSUE TITLE
Song item detected as MusicAlbum instead of Audio in Context Menu

### ISSUE THREAD

**Issue by noaione** [jellyfin/jellyfin-vue#1950]
### Description of the bug

If you try to open the item context menu on the Music Album page for the song, it got detected or marked as `MusicAlbum` instead of `Audio`.

### Steps to reproduce

1. Open a Music Album
2. Click on the context menu for a song (not the album itself)

### Expected behavior

The song is marked as `Audio`.

### Screenshots

https://user-images.githubusercontent.com/34302902/231725309-908a837a-ef54-417d-9c65-47777d5507cc.mp4

Example of a song in an album marked as `MusicAlbum` instead of `Audio`

![Jellyfin](https://user-images.githubusercontent.com/34302902/231725454-04ab8eda-a8b9-40c9-85a7-da8673ec3129.png)

Jellyfin-web version that are correct.

### Platform

Windows

### Browser

Firefox

### Jellyfin server version

10.8.9

### Additional context

Using a modified JF-Vue that are based on https://github.com/jellyfin/jellyfin-vue/commit/16955dd87083d8059b060f57608e084ab2ccf5d0

**Comment by ferferga** [comment]
We don't have the Media Info option implemented in the ItemMenu, so I guess this is something you implemented locally in your branch (hopefully you are interested in contributing it! 🤩). I can't help much without seeing any source, as this is probably an issue in your logic (or a server bug), but to point out where that item is passed to the menu component: https://github.com/jellyfin/jellyfin-vue/blob/master/frontend/src/components/Playback/TrackList.vue#L72

Please, report back

**Comment by noaione** [comment]
> so I guess this is something you implemented locally in your branch (hopefully you are interested in contributing it! 🤩)

Yeah, I'm planning to open PR whenever I completed it

> I can't help much without seeing any source, as this is probably an issue in your logic (or a server bug)

I think it is intended to be `MusicAlbum` yeah, I look up jf-web code and they fetch Item information every time you open the context menu so every data is fetched properly.

I tested with adding `Copy Stream URL` and currently it will not show up in the home screen since it has incomplete data, but it will show up in the item view.

Code here: https://github.com/noaione/jellyfin-vue/tree/feat/more-context-menu (https://github.com/jellyfin/jellyfin-vue/compare/master...noaione:jellyfin-vue:feat/more-context-menu)

**Comment by noaione** [comment]
Honestly, I don't really know. But I managed to fix the problem at least for this issue.

The `item-menu` are using a wrong item.
```diff
-                  <item-menu v-show="isHovering" :item="item" />
+                  <item-menu v-show="isHovering" :item="track" />
```

I'll probably add the fix to my whole PR later.

**Comment by ferferga** [comment]
@noaione Good catch! Link your PR to this issue so it gets closed after it gets merged please!
