### ISSUE TITLE
My Login does not get stored after Browser restart

### ISSUE THREAD

**Issue by hofq** [jellyfin/jellyfin-vue#1957]
### Description of the bug

When i restart my Browser i have to reauthenticate

### Steps to reproduce

1. goto your jellyfin vue instance
2. Enter Credentials to Server
3. Get logged in
4. Restart your Browser
5. Goto your jellyfin vue instance
You have to reauthenticate

### Expected behavior

You stay logged in, at least for like a week, or better: a configurable value

### Platform

Linux

### Browser

Firefox

### Jellyfin server version

10.8.9

**Comment by ferferga** [comment]
Please, fill all the template details accordingly. You're not giving any information in how you deployed your instance.

After doing this, please attach your browser's console logs.

**Comment by hofq** [comment]
It just works now, so i'll close this.
Maybe it was a one time thing
