### ISSUE TITLE
Version from Jellyfin is not high enough

### ISSUE THREAD

**Issue by Catman100** [jellyfin/jellyfin-vue#1958]
### Description of the bug

Im trying to add a default Server in my compose file. The Error tells me the Server from Jellyfin Version must be higher than 10.7.0 the Server Version is 10.8.9.

Manual adding works fine

### Steps to reproduce

1. Adding default Server to docker compose (Additional Context)
2. Start the Conatiner
3. Open the URL in Browser
4. Receive the Error (Screenshot)

### Expected behavior

I should be prompted to log in my Jellyfin (the defined default Server)

### Logs

```text
'''log
==== Starting Jellyfin Vue setup ====
jellyvue  |
jellyvue  | Writing data to /usr/share/nginx/html/config.json...
jellyvue  | DEFAULT_SERVERS value: "https://jelly.domain"
jellyvue  | ROUTER_MODE value: history
jellyvue  |
jellyvue  | ====      Setup finished!        ====
'''
```

### Screenshots

![grafik](https://user-images.githubusercontent.com/87692772/232149251-738fc082-214b-47ee-8658-8182553af315.png)

### Platform

Linux

### Browser

Firefox

### Jellyfin server version

10.8.9

### Additional context

```text
version: "2.1"

services:
  jelly-vue:
    image: ghcr.io/jellyfin/jellyfin-vue:unstable
    container_name: jellyvue
    environment:
      - TZ=Europe/Berlin
      - DEFAULT_SERVERS="https://jelly.domain"
    restart: always
    networks:
      - frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.$SERVICE.rule=Host(`vue.domain`)
      - traefik.http.services.$SERVICE.loadbalancer.server.port=80
      - "traefik.http.routers.$SERVICE.entrypoints=https"
      - "traefik.http.routers.$SERVICE.tls=true"
      - "traefik.http.routers.$SERVICE.tls.certresolver=$TLS"
      - traefik.docker.network=traefik_frontend
networks:
  frontend:
     external: true
     name: traefik_frontend
```

**Comment by ferferga** [comment]
Can you please attach the output of the browser console's?

**Comment by Catman100** [comment]
![grafik](https://user-images.githubusercontent.com/87692772/232209419-9e70ba37-d0e3-45ec-ac96-c12e78c70675.png)

**Comment by ThibaultNocchi** [comment]
Does it work when manually connecting to your server?

**Comment by Catman100** [comment]
> Does it work when manually connecting to your server?

Yes this work

**Comment by ferferga** [comment]
Are you typing the address exactly as the manual one you're using?

**Comment by Catman100** [comment]
Yes this is exactly the same Adress. https;//jelly.domain.de

**Comment by ThibaultNocchi** [comment]
What does the "Network" tab gives you?

**Comment by Catman100** [comment]
![grafik](https://user-images.githubusercontent.com/87692772/232251706-59536424-f170-44a7-80b9-7496896d27e8.png)

**Comment by ferferga** [comment]
@Catman100 Are you still with this issue?

Seems silly, but can you check in Web's dashboard your server version and send a screenshot here?

**Comment by Catman100** [comment]
![Screenshot_20230428_003154_Samsung Internet](https://user-images.githubusercontent.com/87692772/235005380-b8e69884-494a-4bc2-9249-e56d35cf52c4.jpg)

**Comment by ferferga** [comment]
@Catman100 Can you please try with #1989 [deployment's](https://github.com/jellyfin/jellyfin-vue/pull/1989#issuecomment-1530181965)?
