### ISSUE TITLE
Missing info in wiki wrt History Mode

### ISSUE THREAD

**Issue by redxtech** [jellyfin/jellyfin-vue#1974]
### Description of the bug

In the wiki page on configuration, it says that if you want to use history mode you need to configure the webserver to handle this, however the docker container already has the required configuration for this.

It would be great to add a note to the wiki mentioning that you only need additional config if you aren't using the docker container.

### Steps to reproduce

Look at https://github.com/jellyfin/jellyfin-vue/wiki/Configuration#what-you-can-configure

### Expected behavior

Mention that the docker container already handles the webserver config for history mode.

### Platform

Linux

### Browser

Firefox

### Jellyfin server version

10.8.9

**Comment by ferferga** [comment]
Added in https://github.com/jellyfin/jellyfin-vue/wiki/Configuration/f592df327dfc349868bcbce65444cc8e691faeb0
