### ISSUE TITLE
Failed to start episode 

### ISSUE THREAD

**Issue by DoM1niC** [jellyfin/jellyfin-vue#2007]
### Description of the bug

Episode playback failed

### Steps to reproduce

Click on a single episode from the season 

### Expected behavior

-

### Logs

```text
peError: Cannot read properties of undefined (reading 'mdAndUp')
    at index-c1524075.js:88:21605
    at Object.t [as default] (index-c1524075.js:1:15552)
    at Proxy.<anonymous> (index-c1524075.js:78:143739)
    at Th (index-c1524075.js:1:15864)
    at h3.Se [as fn] (index-c1524075.js:1:43801)
    at h3.run (index-c1524075.js:1:4091)
    at q.update (index-c1524075.js:1:44579)
    at lr (index-c1524075.js:1:12653)
    at J2 (index-c1524075.js:1:14285)
Dw @ index-c1524075.js:1
```
![image](https://github.com/jellyfin/jellyfin-vue/assets/1436958/c24b29f0-7742-471c-ae5a-3ca22426e40e)

### Screenshots

![image](https://github.com/jellyfin/jellyfin-vue/assets/1436958/f7e3a21b-c6f7-409a-bbda-afae5d0f2cd8)

### Platform

Windows

### Browser

Chrome

### Jellyfin server version

Unstable

### Additional context

```text
compiled with NodeJS 18 (LTS)
```

**Comment by DoM1niC** [comment]
> > @DoM1niC Your branch is really behind of current master. I believe this was fixed by Vuetify ages ago: https://github.com/vuetifyjs/vuetify/releases/tag/v3.0.4
> 
> Nope is current master ![image](https://user-images.githubusercontent.com/1436958/237186798-57416f4a-a5ba-44c2-8d7b-3b169cce3278.png)

![image](https://github.com/jellyfin/jellyfin-vue/assets/1436958/b477b5b8-2566-4f05-b3ac-ef8c3fa13a4c)

**Comment by ferferga** [comment]
Please give me the exact steps for reproduction, because I can't reproduce it

**Comment by DoM1niC** [comment]
> Please give me the exact steps for reproduction, because I can't reproduce it

I get the error since the last commits of changes on Jellyfin VUE, I only compile the code with `npm install` and `npm run build`, I tried serve too but the issue exist too on local dev preview 

I use Debian SID in Windows Subsystem with nvm to allocate the correct NodeJS Version in this case like NodeJS 18 (LTS)

**Comment by DoM1niC** [comment]
https://github.com/jellyfin/jellyfin-vue/assets/1436958/a18e4a41-dd34-4853-9385-9667ac7c9feb

**Comment by DoM1niC** [comment]
ok I got it was a issue on my code changes .... I restored to origin master for test purpose and all is working.... Sry but THX anyway my friend
