### ISSUE TITLE
Tauri app won't accept HTTP server url

### ISSUE THREAD

**Issue by prayag17** [jellyfin/jellyfin-vue#2009]
### Description of the bug

The tauri client won't take a http:// server.

### Steps to reproduce

Try adding a server with http protocol 

### Expected behavior

The client should behave as normal

### Platform

Windows

### Browser

Chrome

### Jellyfin server version

10.8.10

### Additional context

```text
Tauri blocks XHR requests when in production but allows them in dev build
```

**Comment by endrl** [comment]
Perfect, thank you for reaching out.

**Comment by ferferga** [comment]
@prayag17 PR or indications in how to fix it are appreciated though
