### ISSUE TITLE
"This item can't be played" when trying to play latter songs in a very big music album

### ISSUE THREAD

**Issue by KGT1** [jellyfin/jellyfin-vue#2015]
### Description of the bug

When trying to latter songs play songs in a very big album, the before mentioned altert "This item can't be played" pops up. There dont seem to be any other information in the console or logs. The first few ~250 songs work fine.

### Steps to reproduce

Testet with the following generated album and a fresh install of jellyfin 10.8.10 and vue commit 01a32ce in a newly made music library with default settings:

Generate the Album with the following bash
```
$ mkdir -p "Test Artist/Test Album" && cd "Test Artist/Test Album"`
```
```
#!/bin/bash

for ((i=1; i<=50; i++))
do
    folder_name="Disc $i"
    mkdir "$folder_name"
    echo "Created folder: $folder_name"

    cd "$folder_name"

    for ((j=1; j<=30; j++))
    do
        file_name=$(printf "%02d - Song.flac" $j)
        ffmpeg -f lavfi -i anullsrc=r=11025:cl=mono -t 1 -acodec flac "$file_name" >/dev/null 2>&1
        echo "Created file: $file_name"
    done

    cd ..
done
```

then just try to play a few songs of that album and in the latter songs you should encouter the error.

### Expected behavior

The songs should play like any other song in smaller albums.

### Platform

Linux

### Browser

Firefox

### Jellyfin server version

10.8.10

### Additional context

```text
This Issue is also seems to be present in the default web client, but is not present in most 3rd party clients.
```

**Comment by ferferga** [comment]
@KGT1 I have a 2 hour+ FLAC of over 300 MB in my library that plays fine in Vue, so it's unlikely this issue is caused by the length of the track.

After adding the music library, did you run a library scan through the scheduled task and waited for it to finish successfully? Wonky things can happen while an item being played is also being parsed and scanned.

If that's the case, please reproduce the error and copy and paste here your browser's console output of the error.
Thank you very much in advance.

**Comment by KGT1** [comment]
Thanks for the quick response. I meant big more as in many files instead of filesize. the bash above should only generate 1s flac files. The length of tracks dont seem to be a problem on my end either.

I wasnt sure if i did let it run through, so i redid the whole steps to reproduce again and it still had the error.

The problem is, that there dont seem to be any console errors when encountering the altert. Ill post a video below.

https://github.com/jellyfin/jellyfin-vue/assets/29805814/d774a85d-a0c5-4942-b93c-2af1d5d1ccfe

**Comment by ferferga** [comment]
@KGT1 Can you please try building and running your own instance with this line removed?
 https://github.com/jellyfin/jellyfin-vue/blob/master/frontend/src/store/playbackManager.ts#L1064

**Comment by KGT1** [comment]
Definitely fixed the issue, but i of course dont know if there was another reason why the limit was there.

Performance is of course a little slow, but i think that is to be expected with such big albums.

Thanks for the help @ferferga 

If fixed this issue can be closed.
