### ISSUE TITLE
Jf-vue client does not show an error if the jf-vue server is offline

### ISSUE THREAD

**Issue by mmonj** [jellyfin/jellyfin-vue#2030]
### Description of the bug

If the server that hosts the jf-vue site gets disabled, and then a person tries to visit the jf-vue site, the site will continually load without showing any error messages indicating that there was a problem reaching the server. 

It will just continually load, as follows:

https://github.com/jellyfin/jellyfin-vue/assets/68614941/1c124c46-9c0a-4d8f-838a-62819ee583d6

### Steps to reproduce

* Killed the docker container that hosts jf-vue
* Visited the domain that normally hosts jf-vue
* The page loads (from cache i assume) and continually loads, but never shows an error to the user

### Expected behavior

The jf-vue client should indicate that there was an error reaching the server

### Platform

Linux

### Browser

Chrome

### Jellyfin server version

10.8.0

**Comment by ferferga** [comment]
Yes it does - However, in this case, it's not the Jellyfin server that's offline, it's the server that it's serving the client itself. We can't control how and when the browser caches, so this is not something we can handle gracefully. 


You're not indicating anywhere if you're running from master, unstable or from stable-rc. If you've been running Vue from quite sometime, you're probably stuck with the old service worker that had the PWA running: Go to F12 (Developer Tools) > Application > Service Workers and unregister all of them. That should fix the issue for you, if it doesn't, please let me know and reopen this.
