### ISSUE TITLE
Wrong version error message: "Server version needs to be 10.7.0 or higher", requested version is hardcoded.

### ISSUE THREAD

**Issue by rolandogdp** [jellyfin/jellyfin-vue#2037]
### Description of the bug

When trying to add a server on the https://jellyfin-vue.example.org/server/add landing page, adding the url of a server behind a reverse proxy that only exposes ports 80 and 443 as per  [official jellyfin documentation](https://jellyfin.org/docs/general/networking/#running-jellyfin-behind-a-reverse-proxy) an error will be thrown saying the server version is too low. 

When looking into the console, a CORS error is thrown, but the target URL was changed from https://jellyfin.example.org/System/Info/Public to https://jellyfin.example.org:8096/System/Info/Public
and a second CORS error but this time trying the 8920 port. 

The frontend seems to manually add the port to the provided URL thus making it unable to connect.

Requesting https://jellyfin.example.org/System/Info/Public actually yields the correct JSON answer with all the public information of the instance. 

The code seems to first test for port 8096, then the user provided, then 8920 even if the user provided URL works. The error thrown by the invalid URLs seem to then throw a Server version too low.

### Steps to reproduce

- Start a jellyfin instance behind a Traefik reverse proxy and only allow port 443 while using hostnames. 

- Start a jellyfin-vue instance locally or use remote one. 

- Add your server url to your jellyfin instance

- Get error

### Expected behavior

The expected behavior would be to trust the URL provided by the user with highest priority and then fall bakc to hard coded ports in case of error. 

### Logs

```text
XHRGET
https://jellyfin.example.org:8096/System/Info/Public
CORS Failed

XHRGET
https://jellyfin.example.org/System/Info/Public
[HTTP/2 200 OK 80ms]

XHRGET
https://jellyfin.example.org:8920/System/Info/Public
CORS Failed

Blocage d’une requête multiorigine (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://jellyfin.example.org:8096/System/Info/Public. Raison : échec de la requête CORS. Code d’état : (null).

Blocage d’une requête multiorigine (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://jellyfin.example.org:8920/System/Info/Public. Raison : échec de la requête CORS. Code d’état : (null).

Error: Server version is too low
    connectServer https://jf-vue.pages.dev/assets/index-85e908f7.js:69
    u https://jf-vue.pages.dev/assets/index-85e908f7.js:82
    qo https://jf-vue.pages.dev/assets/index-85e908f7.js:1
    gs https://jf-vue.pages.dev/assets/index-85e908f7.js:1
    Ha https://jf-vue.pages.dev/assets/index-85e908f7.js:1
    VR https://jf-vue.pages.dev/assets/index-85e908f7.js:1
    s https://jf-vue.pages.dev/assets/index-85e908f7.js:73
    gs https://jf-vue.pages.dev/assets/index-85e908f7.js:1
    Ha https://jf-vue.pages.dev/assets/index-85e908f7.js:1
    n https://jf-vue.pages.dev/assets/index-85e908f7.js:1
index-85e908f7.js:1:13553
    DR https://jf-vue.pages.dev/assets/index-85e908f7.js:1
    Sm https://jf-vue.pages.dev/assets/index-85e908f7.js:1
    Ha https://jf-vue.pages.dev/assets/index-85e908f7.js:1
    (Asynchrone : promise callback)
    Ha https://jf-vue.pages.dev/assets/index-85e908f7.js:1
    VR https://jf-vue.pages.dev/assets/index-85e908f7.js:1
    s https://jf-vue.pages.dev/assets/index-85e908f7.js:73
    gs https://jf-vue.pages.dev/assets/index-85e908f7.js:1
    Ha https://jf-vue.pages.dev/assets/index-85e908f7.js:1
    n https://jf-vue.pages.dev/assets/index-85e908f7.js:1
```

### Platform

Linux

### Browser

Firefox

### Jellyfin server version

"10.8.8"

**Comment by rolandogdp** [comment]
I have tested it with the online hosted instance: https://jf-vue.pages.dev/#/server/add , a self hosted instance on the same server and domain that is running the jellyfin instance with jellyfin/jellyfin-vue:unstable@sha256:a9bc45f60686ad166ec631482a0734b61353f00b0d938f3c646408ef534e87a1 as the front end docker image and linuxserver/jellyfin@sha256:0e071117c6421b3270809de024f251040537d9b02f47727ecb42a494a2f61e80 as the backend jellyfin server, and finally also tested running locally the frontend and still the same issue.

**Comment by rolandogdp** [comment]
After further testing multiple versions online. It seems to be this from this merge request that the problem started happening: https://github.com/jellyfin/jellyfin-vue/pull/2004

As the version from this pull request: https://github.com/jellyfin/jellyfin-vue/pull/2003 works perfectly. I hope this can help you narrow the problem.

**Comment by ferferga** [comment]
@rolandogdp If you connect to the demo instance, you will be able to connect (albeit the expected CORS errors that, as I told before, are gracefully handled.

If you connect to the demo instance, you will be able to connect (albeit the expected CORS errors that, as I told before, are gracefully handled.

If you look into the code, here's the only place where that notification is displayed: https://github.com/jellyfin/jellyfin-vue/blob/master/frontend/src/plugins/remote/auth/index.ts#L132

The issues are returned by the SDK: https://github.com/jellyfin/jellyfin-sdk-typescript/blob/master/src/discovery/recommended-server-discovery.ts#L40

I don't find anything wrong in this logic. Can you share the payload of Public?  It displays a 200 code as it should, but without the payload is useless info.

The linked PR is completely irrelevant to this, it's impossible that changed something.

**Comment by rolandogdp** [comment]
Sure this is the full request with the domain name replaced and IP address replaced. If you would like the real domain name, feel free to instruct me how to send it to you privately as I don't feel comfortable with it being public.
`Request URL:
https://jellyfin.example.org/System/Info/Public
Request Method:
GET
Status Code:
200
Remote Address:
-:443
Referrer Policy:
strict-origin-when-cross-origin
Access-Control-Allow-Origin:
*
Content-Encoding:
br
Content-Type:
application/json; charset=utf-8
Date:
Fri, 09 Jun 2023 18:00:48 GMT
Server:
Kestrel
Vary:
Accept-Encoding
X-Response-Time-Ms:
3
:Authority:
jellyfin.example.org
:Method:
GET
:Path:
/System/Info/Public
:Scheme:
https
Accept:
application/json, text/plain, */*
Accept-Encoding:
gzip, deflate, br
Accept-Language:
en-US,en;q=0.9
Origin:
https://jf-vue.pages.dev
Referer:
https://jf-vue.pages.dev/
Sec-Ch-Ua:
"Not.A/Brand";v="8", "Chromium";v="114"
Sec-Ch-Ua-Mobile:
?0
Sec-Ch-Ua-Platform:
"Linux"
Sec-Fetch-Dest:
empty
Sec-Fetch-Mode:
cors
Sec-Fetch-Site:
cross-site
User-Agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36`

**Comment by rolandogdp** [comment]
> @rolandogdp If you connect to the demo instance, you will be able to connect (albeit the expected CORS errors that, as I told before, are gracefully handled.
> 
> If you connect to the demo instance, you will be able to connect (albeit the expected CORS errors that, as I told before, are gracefully handled.

However even if one of the queries does indeed return a code 200, it is impossible to proceed as it throws the  “Server version needs to be 10.7.0 or higher”. 

I don't know what may have changed in the quoted pull requests, but one is working without issues and after that the issue arise. (Meaning https://efdfeb23.jf-vue.pages.dev/ is the last version I am able to select my server.

**Comment by ferferga** [comment]
@rolandogdp Can you contact me in Matrix?

**Comment by rolandogdp** [comment]
@ferferga Yes I have sent you a DM.

**Comment by rolandogdp** [comment]
After some digging with the help of @ferferga the issue was that the required backend server version was bumped to 10.8.10 in [here](https://github.com/jellyfin/jellyfin-sdk-typescript/blob/master/src/versions.ts#L8). The error message however still shows "Server version needs to be 10.7.0 or higher". It seems the version error message was hard coded and should be updated.
