### ISSUE TITLE
DEFAULT_SERVERS docker container at runtime not working

### ISSUE THREAD

**Issue by cpaczek** [jellyfin/jellyfin-vue#2065]
### Description of the bug

This seems pretty undocumented but I am wanting to host my own version of jellyfin-vue for my friends and family but I don't want them to have to input the server name to login. After a bit of digging I found DEFAULT_SERVERS env var which sounds perfect. I went ahead and use the jellyfin/jellyfin-vue:unstable-static with the runtime variable and unfortunately  it still prompted me to add a server. 

### Steps to reproduce

Create a new container using the jellyfin/jellyfin-vue:unstable-static release.

add DEFAULT_SERVERS=yourdomain to the runtime variables

### Expected behavior

I expect it to either just allow me to select the server or just bring me to the login page. 

### Screenshots

![image](https://github.com/jellyfin/jellyfin-vue/assets/25715982/b8009a81-bdfa-46cc-9eeb-6eb7694df631)

### Platform

Linux

### Browser

Chrome

### Jellyfin server version

10.8.10

### Additional context

I am not 100% sure why this doesn't work but my guess would be maybe jellyfin-vue only supports modifying the default_servers at buildtime and not runtime? If that's true it would be great to get runtime feature built in but in the meantime I can just build the image myself.

**Comment by ferferga** [comment]
@cpaczek You're using an ancient version, the correct tag is `unstable`

**Comment by DesertCookie** [comment]
I am using `unstable` and have been unable to get a different behaviour from `DEFAULT_SERVERS` than what I've gotten for months: nothing.  
I've been monitoring https://github.com/jellyfin/jellyfin-vue/issues/1783 for a while now.
