### ISSUE TITLE
Server not found: document is not defined

### ISSUE THREAD

**Issue by DesertCookie** [jellyfin/jellyfin-vue#2066]
### Description of the bug

Jellyfin Vue SSR does not work with `DEFAULT_SERVERS` and throws a document error, complaining the server does not exist.

### Steps to reproduce

Set up two containers in unRAID: one `lscr.io/linuxserver/jellyfin:latest` and `jellyfin/jellyfin-vue:unstable-ssr`. The former on `streambackend.example.com` and the other on `stream.example.com`. Point the latter to the Jellyfin server URL using `DEFAULT_SERVERS`.

### Expected behavior

Jellyfin Vue SSR should not throw a document error.

**Solution**: Not using SSR (only `unstable`) works as expected.

### Logs

```text
ERROR  document is not defined

  at server.js:179080:33
  at Module.<anonymous> (node_modules/screenfull/index.js:66:0)
  at __webpack_require__ (webpack/bootstrap:25:0)
  at Module.<anonymous> (src/layouts/default.vue)
  at __webpack_require__ (webpack/bootstrap:25:0)
  at Object.<anonymous> (server.js:134735:18)
  at __webpack_require__ (webpack/bootstrap:25:0)
  at server.js:118:18
  at Object.<anonymous> (server.js:121:10)
  at o (/node_modules/vue-server-renderer/build.prod.js:1:77799)
```

There are no logs in Jellyfin.
```


### Screenshots

_No response_

### Platform

Linux

### Browser

Firefox

### Jellyfin server version

10.8.10

### Additional context

```text
I'm unaware if this is known already or even expected. Thought I should definitely report it.
```

**Comment by ferferga** [comment]
Only latest tags are supported, SSR is long deprecated: https://github.com/jellyfin/jellyfin-vue/discussions/1620

**Comment by DesertCookie** [comment]
Alright, makes sense after what I've read after posting this.

It's still prominently on the unRAID app store. I'll try to contact someone to take it off as it is the first result for `jellyfin vue`.
