### ISSUE TITLE
Allow installation in a sub-path

### ISSUE THREAD

**Issue by Salamandar** [jellyfin/jellyfin-vue#2085]
### Description of the bug

For now it seems that jellyfin-vue is only installable on a domain root (localhost:8080/, jf-vue.pages.dev) and can't be installed in a subpath (mydomain.tld/jellyfin-vue/). `/config.json` is accessed via absolute path.

See https://github.com/jellyfin/jellyfin-vue/blob/0a01f80b44072248cf771ff1f0cebba8ddf741ea/frontend/src/utils/external-config.ts#L51

According to https://vitejs.dev/guide/build.html#public-base-path, I suppose you should use `import.meta.env.BASE_URL`.

### Steps to reproduce

```
npm install
npm run build -- --base=/jellyfin-vue/
```

Configure nginx with a subdirectory
Enjoy an empty page.
See in the requests panel of Firefox: `GET | https://mydomain.tld/config.json` while all other resources are accessed via `https://mydomain.tld/jellyfin-vue/<resource path>`.

### Expected behavior

config should be retrieved via `GET | https://mydomain.tld/jellyfin-vue/config.json`

### Platform

Linux

### Browser

Firefox

### Jellyfin server version

10.8.10

**Comment by ferferga** [comment]
This is not a problem of Jellyvin Vue, but rather a webserver configuration issue. In nginx, try to add this to your location block:

```
rewrite ^/subpath/(.*) /$1 break;
```

**Comment by Salamandar** [comment]
I’m pretty sure that won’t fix my issue, unless that patches the content of the files downloaded from the server.

Here, jellyfin-vue tries to access `https://mydomain.tld/config.json`, but it doesn’t exist. The configuration file is accessible at `https://mydomain.tld/jellyfin-vue/config.json`.

The only way to fix the issue is to fix the source files of jellyfin-vue.

**Comment by ferferga** [comment]
@Salamandar You're specifying urls using history mode, which is [not the default behaviour](https://github.com/jellyfin/jellyfin-vue/blob/master/frontend/public/config.json#L3) 

Do you also have the try_files directive as specified in the Vue Router config and mentioned [here](https://github.com/jellyfin/jellyfin-vue/wiki/Configuration#what-you-can-configure)?

**Comment by Salamandar** [comment]
No, I’m in hash mode. What makes you think i’m in history mode ?

Also, yes, i’m using the configuration suggested by the Vue documentation.

**Comment by ferferga** [comment]
@Salamandar My bad for not replying earlier, thought that I did.

I initially misunderstood the problem, you are completely right that no history mode could be used without ``config.json`` in ^^.

Fix shipped now!
