### ISSUE TITLE
Server Not Found Error Message

### ISSUE THREAD

**Issue by definedlegend** [jellyfin/jellyfin-vue#2092]
### Description of the bug

Upon Login I am presented with a Server Not Found Red Message in the bottom left hand corner. This doesn't affect the actual performance of the application but just a visual bug from what I see.

### Steps to reproduce

1. Login
2. Presented with Message "server not found" in bottom left-hand corner

### Expected behavior

Login with no error messages

### Platform

Linux

### Browser

Chrome

### Jellyfin server version

10.8.10

**Comment by T-R-I-X** [comment]
bump

**Comment by ozkansoyturk** [comment]
same

**Comment by ferferga** [comment]
@definedlegend @ozkansoyturk @T-R-I-X a video it's much welcome + additional details (such as if there are multiple servers configured, if there are default servers on config.json file, etc...)

**Comment by ferferga** [comment]
Closed due to the lack of reproduction details
