### ISSUE TITLE
DEFAULT_SERVERS in docker container not taken at first site visit

### ISSUE THREAD

**Issue by stargazze** [jellyfin/jellyfin-vue#2117]
### Description of the bug

Hello
I host my own jellyfin-vue in a docker container that I share with some friends. I included a `DEFAULT_SERVERS` environment variable so that people can directly log in without server input. However at first site visit at `jellyfin-vue.domain.tld`, we are redirected to `jellyfin-vue.domain.tld/server/add` and the server is asked. If I manually delete "server/add" to refresh page to `jellyfin-vue.domain.tld`, then the default server seems to be taken.

### Steps to reproduce

- Create a new jellyfin-vue container with the following `docker-compose.yml`:
 ```
version: "2.3"
 services:
    jellyfin-vue:
      image: ghcr.io/jellyfin/jellyfin-vue:unstable
      ports:
        - 9680:80
      restart: "unless-stopped"
      environment:
        - DEFAULT_SERVERS=https://jellyfin.domain.tld
```
- Configure reverse proxy to point jellyfin-vue.domain.tld to port 9680
- Visit jellyfin-vue.domain.tld

### Expected behavior

Th user is invited to login on the default server at first visit. The server is not asked (taken from `DEFAULT_SERVERS`) and the user doesn't need to refresh page.

### Logs

```text
Attaching to jellyfin-vue_jellyfin-vue_1
jellyfin-vue_1  | ==== Starting Jellyfin Vue setup ====
jellyfin-vue_1  | 
jellyfin-vue_1  | Writing data to /usr/share/nginx/html/config.json...
jellyfin-vue_1  | DEFAULT_SERVERS value: https://jellyfin.domain.tld
jellyfin-vue_1  | ROUTER_MODE value: history
jellyfin-vue_1  | 
jellyfin-vue_1  | ====      Setup finished!        ====
jellyfin-vue_1  | 
jellyfin-vue_1  | 
jellyfin-vue_1  | 2023/10/21 18:59:26 [notice] 1#1: using the "epoll" event method
jellyfin-vue_1  | 2023/10/21 18:59:26 [notice] 1#1: nginx/1.24.0
jellyfin-vue_1  | 2023/10/21 18:59:26 [notice] 1#1: built by gcc 12.2.1 20220924 (Alpine 12.2.1_git20220924-r4) 
jellyfin-vue_1  | 2023/10/21 18:59:26 [notice] 1#1: OS: Linux 5.15.0-86-generic
jellyfin-vue_1  | 2023/10/21 18:59:26 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
jellyfin-vue_1  | 2023/10/21 18:59:26 [notice] 1#1: start worker processes
jellyfin-vue_1  | 2023/10/21 18:59:26 [notice] 1#1: start worker process 9
jellyfin-vue_1  | 2023/10/21 18:59:26 [notice] 1#1: start worker process 10
jellyfin-vue_1  | 2023/10/21 18:59:26 [notice] 1#1: start worker process 11
jellyfin-vue_1  | 2023/10/21 18:59:26 [notice] 1#1: start worker process 12
jellyfin-vue_1  | 2023/10/21 18:59:26 [notice] 1#1: start worker process 13
jellyfin-vue_1  | 2023/10/21 18:59:26 [notice] 1#1: start worker process 14
jellyfin-vue_1  | 2023/10/21 18:59:26 [notice] 1#1: start worker process 15
jellyfin-vue_1  | 2023/10/21 18:59:26 [notice] 1#1: start worker process 16
jellyfin-vue_1  | 2023/10/21 18:59:26 [notice] 1#1: start worker process 17
jellyfin-vue_1  | 2023/10/21 18:59:26 [notice] 1#1: start worker process 18
jellyfin-vue_1  | 2023/10/21 18:59:26 [notice] 1#1: start worker process 19
jellyfin-vue_1  | 2023/10/21 18:59:26 [notice] 1#1: start worker process 20
jellyfin-vue_1  | 2023/10/21 18:59:26 [notice] 1#1: start worker process 21
jellyfin-vue_1  | 2023/10/21 18:59:26 [notice] 1#1: start worker process 22
jellyfin-vue_1  | 2023/10/21 18:59:26 [notice] 1#1: start worker process 23
jellyfin-vue_1  | 2023/10/21 18:59:26 [notice] 1#1: start worker process 24
jellyfin-vue_1  | 192.168.16.1 - - [21/Oct/2023:18:59:40 +0000] "GET / HTTP/1.1" 200 3086 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/118.0" "***.***.***.**"
```

### Screenshots

At first visit:
![jellyfin-vue01](https://github.com/jellyfin/jellyfin-vue/assets/37485105/4957d5eb-cc41-4ac9-b42b-e86d940237bf)

At second visit:
![jellyfin-vue02](https://github.com/jellyfin/jellyfin-vue/assets/37485105/9485d1f2-fb21-48e9-b3dc-54576abd443f)

### Platform

Linux

### Browser

Firefox

### Jellyfin server version

10.8.11

### Additional context

Tested with firefox and Chromium

**Comment by ThowZzy** [comment]
Can confirm

**Comment by kimboslice99** [comment]
> Can confirm.
> 
> It seems that you need a cookie that is created **after** the first visit. (Just assuming)
> 
> So as a workaround right now, you need to first visit the page and then delete "/server/login" from the url and hit enter.

Not cookies. its browser storage.

Heres a real workaround, Load jellyfin-vue and do not log in, just wait for the auth key to populate then grab the value of the key and use it here, place before any other script tag in index.html

```
  <script>
  var prompt_auth = 'enter_key_info';
  var prompt_storage = localStorage.getItem('auth');
  var prompt_auth_parsed = JSON.parse(prompt_auth);
  if(prompt_storage && prompt_storage.includes(prompt_auth_parsed.servers[0].ServerName)){
	console.log('set');
  } else {
    localStorage.setItem('auth', prompt_auth);
    console.log('not set');
  }
  </script>
```

**Comment by stargazze** [comment]
> > Can confirm.
> > It seems that you need a cookie that is created **after** the first visit. (Just assuming)
> > So as a workaround right now, you need to first visit the page and then delete "/server/login" from the url and hit enter.
> 
> Not cookies. its browser storage.
> 
> Heres a real workaround, Load jellyfin-vue and do not log in, just wait for the auth key to populate then grab the value of the key and use it here, place before any other script tag in index.html
> 
> ```
>   <script>
>   var prompt_auth = 'enter_key_info';
>   var prompt_storage = localStorage.getItem('auth');
>   var prompt_auth_parsed = JSON.parse(prompt_auth);
>   if(prompt_storage && prompt_storage.includes(prompt_auth_parsed.servers[0].ServerName)){
> 	console.log('set');
>   } else {
>     localStorage.setItem('auth', prompt_auth);
>     console.log('not set');
>   }
>   </script>
> ```

Thanks, that fixes it for now.
