### ISSUE TITLE
Too much loading time if there are many media

### ISSUE THREAD

**Issue by GermanMFB** [jellyfin/jellyfin-vue#2186]
### Description of the bug

When there are many media in a library, it takes too long to display all of them, the solution would be to filter 100 media per page or something like that.

### Steps to reproduce

2000+ media files

### Expected behavior

Less time load

### Platform

Linux

### Browser

Other (Please specify in the "additional context" section)

### Jellyfin server version

all

### Additional context

```text
Every nav
```

**Comment by ferferga** [comment]
Dplicate of #762
