### ISSUE TITLE
quality and speed selector disabled

### ISSUE THREAD

**Issue by tippfehlr** [jellyfin/jellyfin-vue#2226]
### Description of the bug

I can’t select or view the quality (or speed) of media

### Steps to reproduce

1. play any video
2. click on playback settings

### Expected behavior

- Current quality and speed is displayed
- quality and speed can be selected

### Screenshots

![image](https://github.com/jellyfin/jellyfin-vue/assets/46620049/00f753c3-f14e-409b-b8a2-e77e7e63ae05)

### Platform

Linux

### Browser

Firefox

### Jellyfin server version

10.8.13

### Additional context

```text
also tested on Brave
```

**Comment by ferferga** [comment]
ToDo list:

- [ ] Quality
- [x] Speed
