### ISSUE TITLE
Images won't load in Safari

### ISSUE THREAD

**Issue by felix920506** [jellyfin/jellyfin-vue#2291]
### Description of the bug

Images won't load properly in safari and only show a blurred version.

### Steps to reproduce

1. Connect JF vue to a server and login in Safari. (Using the hosted instance)
2. See Error

### Expected behavior

Images should render after at most a few seconds

### Platform

macOS

### Browser

Safari

### Jellyfin server version

10.8.13

**Comment by ferferga** [comment]
@felix920506 I tested the PR in BrowserStacks, but if you can test in a real device, much better.
