### ISSUE TITLE
Cast & Crew Headshot Images Stretched

### ISSUE THREAD

**Issue by Jamie-TinyPixel** [jellyfin/jellyfin-vue#2295]
### Description of the bug

The Cast / Crew photo headshots are stretehed to fit into a perfect square, it seems like, most likely as a result of Jellyfin Regular downloading them in a non-square aspect. 

### Steps to reproduce

1. Enter any TV Show / Film
2. See Crew/Cast images
3. See issue
4. (_optional_) Click on any member of cast
5. See issue

### Expected behavior

The images should be cropped accordingly, possibly losing the lower half of the image where the Cast member's face is unlikely to be.
Or, square images could be downloaded as part of Jellyfin

### Screenshots

![image](https://github.com/jellyfin/jellyfin-vue/assets/77833819/b36fca92-4076-421a-a063-24d8a204dbbf)
![image](https://github.com/jellyfin/jellyfin-vue/assets/77833819/8658e7fb-d9b3-425e-831e-a7c856d2588a)

### Platform

Linux

### Browser

Chrome

### Jellyfin server version

10.8.13

**Comment by ferferga** [comment]
You're using a [commit from a month ago](https://github.com/jellyfin/jellyfin-vue/commit/22615a15655494fe5e6dfa5af2ccacc1df75d1f7), please look into Docker images auto updating with watchtower.

This was fixed in

**Comment by Jamie-TinyPixel** [comment]
Jesus christ - did not see this. 

sorry for the duplicate issue!
