### ISSUE TITLE
Doesn't work with Safari Lockdown Mode (solution "deselect the Enable Lockdown Mode checkbox") 

### ISSUE THREAD

**Issue by GETandSELECT** [jellyfin/jellyfin-vue#2299]
### Description of the bug

Doesn't work with Safari Lockdown Mode (solution "deselect the Enable Lockdown Mode checkbox") 

You don't see the screen to choose server

<img width="603" alt="lockdown_mode_Sonoma_Safari" src="https://github.com/jellyfin/jellyfin-vue/assets/10598483/941abb74-7510-4184-a3fd-3572d91e9aa4">

### Steps to reproduce

latest macOS and Lockdown Mode https://support.apple.com/en-jo/105120

### Expected behavior

works with lockdown mode / this issue more an info for others / there are other browsers on macOS with no issues

### Platform

macOS

### Browser

Safari

### Jellyfin server version

10.8.13

### Additional context

Feel free to close this bug with "Won't do", more an info to upstream.

**Comment by ferferga** [comment]
First time I hear that this exists

I don't have any Apple device (I could borrow my sister's, but that's not ideal), so my testing is limited to BrowserStacks (and, iirc, in our current plan we are limited to just the browser and we can't modify any of the device's settings)

I can try my best to improve this situation though. Just to discard the basics — are you using the hosted instance and connecting to your server? What if you use Docker and, with a reverse proxy, serve the frontend in the same address as the server? My guess it's this "lockdown" mode just blocks all requests that are not from the same origin of the window.

**Comment by ferferga** [comment]
But what happens if Vue is also served by the Jellyfin server?

**Comment by ferferga** [comment]
Closing due to the lack of further input, comment again if this needs to be reopened again
