### ISSUE TITLE
Cant extiv play window in browser

### ISSUE THREAD

**Issue by ksb749** [jellyfin/jellyfin-vue#2473]
### Description of the bug

Running Jellyfin 10.10.0-unstable and latest jellyfin-vue in docker.

When i play content in Jellyfin-vue and wish to exit the player, the media stops, but im stuck at the player window - Currently only thing i can do is change the URL from: http://local.ip:8645/playback/video to http://local.ip:8645

### Steps to reproduce

Start playing media and press the x in top left corner of the player window.

### Expected behavior

blank player window

### Platform

Linux

### Browser

Chrome

### Jellyfin server version

10.10.0-unstable

**Comment by ferferga** [comment]
Can you record a video please?

**Comment by ksb749** [comment]
I upgraded Jellyfin server and suddenly the issue was gone.

**Comment by ksb749** [comment]
The issue seems to have been in the Jellyfin server, i upgraded it earlier today and afterwards there is no issue.
