### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by Anan5a** [jellyfin/jellyfin-vue#261]
I am confused, 
How is this different from @jellyfin/jellyfin-web ?

**Comment by Camc314** [comment]
See 
https://github.com/jellyfin/jellyfin-web/issues/889
And 
https://github.com/jellyfin/jellyfin-web/issues/1901

**Comment by Extarys** [comment]
@Anan5a Came here after seeing the -web framework migration.

@jellyfin/jellyfin-web > Legacy, current web version
@jellyfin/jellyfin-vue > Being developed, new UI, the future
:rocket: :heart:
