### ISSUE TITLE
The user selection placeholder icon doesn't look right with the light theme

### ISSUE THREAD

**Issue by MrTimscampi** [jellyfin/jellyfin-vue#374]
On the user selection page (when there are public users on the server), when using the light mode, the placeholder icon doesn't look right.

![image](https://user-images.githubusercontent.com/19396809/101749060-96f0c400-3acd-11eb-9e22-58cb80bd3d83.png)

It should likely still use the dark theme at the component level.

**Comment by sarab97** [comment]
![image](https://user-images.githubusercontent.com/21101369/102154610-c32a8d00-3e9f-11eb-9e6f-6d373d5bf4b5.png)

the user icon seems to use right theme. When using light theme its color is dark and when using dark theme its color is light.

In this image right side user i have changed its css from inspect tools.

**Comment by sarab97** [comment]
> > the user icon seems to use right theme. When using light theme its color is dark and when using dark theme its color is light.
> 
> And that's the issue :) It should always use the `dark` theme. It's basically a one-line fix, but it's not a priority and is a good opportunity to help people figure out the structure of the client and Vuetify, hence it not being fixed already.

well its one word fix then basically ;)
