### ISSUE TITLE
Item select version & video ist broken

### ISSUE THREAD

**Issue by schmidex** [jellyfin/jellyfin-vue#462]
First of all thanks for your hard work. This looks very promising!
Just want to let you know, that I came across a small bug on the item page.
See screenshot.
https://github.com/jellyfin/jellyfin-vue/blob/96c1210a5c8092bb6f84f16d04448393792979d6/pages/item/_itemId/index.vue#L126 needs to be ```{{ i.value.Name}}```. But I couldn't figure out how to fix the dropdown :-(
The Label of the version-select is also wrong (says 'Video').

![select](https://user-images.githubusercontent.com/2202857/103284459-91571180-49db-11eb-9a20-419ec5cb8e89.PNG)

**Comment by ThibaultNocchi** [comment]
I'm looking into it, I surely broke that recently :)

**Comment by schmidex** [comment]
thanks for the quick fix.
Another thing I noticed now: When selecting another version in the dropdown the other options don't update accordingly.
For example: When I change the version from a 4K to a 1080p source, the video still says "4K HEVC HDR"."

**Comment by ThibaultNocchi** [comment]
I think it was never implemented, am I right?

**Comment by MrTimscampi** [comment]
It is indeed not implemented yet. The selectors are "just for show", in order to have them visually on the page for design purposes.
