### ISSUE TITLE
Some letters getting clipped in height

### ISSUE THREAD

**Issue by ThibaultNocchi** [jellyfin/jellyfin-vue#470]
I leave this up here to take note of what I found
***
On my computer, letters which take some height are getting clipped.
![print_screen_2020-12-31-16-47-34](https://user-images.githubusercontent.com/1619359/103416703-14b56600-4b88-11eb-81b7-2ab477db7686.png)
![print_screen_2020-12-31-16-47-29](https://user-images.githubusercontent.com/1619359/103416704-154dfc80-4b88-11eb-9ada-34412638bcf4.png)
![print_screen_2020-12-31-16-47-16](https://user-images.githubusercontent.com/1619359/103416706-15e69300-4b88-11eb-9558-782023137c44.png)

It happens with all kind of letters, "y", "ç", etc. Here is what I found:

* Happens with `noto-sans` but not with `sans-serif`
* Happens on FF 84, Lubuntu 20.10 with 1080p screen
* Doesn't happen on Chrome, Windows 10, 1080p screen at neither 125% or 100% display settings (not the browser's zoom, the Windows display settings)
* Doesn't happen on Chrome and FF on Android
* Unzooming or zooming a few steps in the browser makes the letters appear fully (but the zoom levels aren't the same for all components, 90% works for the "g" in "settings" but not for the "g" in "English")
* Computed `line-height` is similar to others

Confirmed user where it works:
* @MrTimscampi 
* @ferferga 

Confirmed user where it doesn't work:
* @ThibaultNocchi 

As PR #467 shows, setting `line-height: normal !important;` to concerned components fixes it.

***
These are my results as of 2020/12/31.

**Comment by ferferga** [comment]
Wasn't able to reproduce before, but it seems that bigger text still faces the same issue (see how letter **g** looks partially cropped):

![image](https://user-images.githubusercontent.com/10274099/104920942-e2ce3d00-5998-11eb-9b7f-139088d34bbb.png)
