### ISSUE TITLE
Error: Redirected when going from "/" to "/login" via a navigation guard.

### ISSUE THREAD

**Issue by ferferga** [jellyfin/jellyfin-vue#481]
This console error is happening when inputting the server address and going to the username/password field. Happens exactly in the second where the server selection screen appears.

I think this is caused due to using routes instead of letting axios do auth completely

**Comment by MrTimscampi** [comment]
It's because of a navigation guard, this is normal, expected behavior.

**Comment by MrTimscampi** [comment]
Actually, we might be redirecting to / after being on /login. But this has nothing to do with Axios :) It's a vue-router thing.

**Comment by ferferga** [comment]
@MrTimscampi we shouldn't report this as an error in console though

**Comment by ferferga** [comment]
Upstream issue at: https://github.com/nuxt-community/auth-module/issues/731

**Comment by Camc314** [comment]
Closing as the error is no longer present.
