### ISSUE TITLE
Videos should be centered horizontally in the fullscreen player

### ISSUE THREAD

**Issue by MrTimscampi** [jellyfin/jellyfin-vue#486]
As reported by @sparky8251 , videos are currently aligned to the left of the maximized video player:
![image](https://user-images.githubusercontent.com/19396809/103482858-9a811d80-4de3-11eb-9db0-3b2620711c69.png)

**Comment by sparky8251** [comment]
For a smidge more info (though I doubt its too useful), the above video is 1080p while the monitor is 1440p and 21:9.
