### ISSUE TITLE
Replace "You may also like"

### ISSUE THREAD

**Issue by Darkwolf1515** [jellyfin/jellyfin-vue#539]
Yes, this is the most petty of non issues, but personally I think it would sound better as "Related items" or "similar to what you're watching/listening. Since there's a 99% chance that if I took the time to add it to my server, I like it,

**Comment by MrTimscampi** [comment]
While the admin adds things and obviously like them, this is not always the case.

Jellyfin is built for multi-user usage, and usually, these users won't have control over what's there. Even for admins, some of us have large libraries and don't curate content to a level where we know we'll like everything.

In general, we try to steer towards a more "discoverable" way of presenting your library in this client, which implies making recommendations on various things, this being one of them.

**Comment by Darkwolf1515** [comment]
Alright, if that's how it is then that's how it is, thank you. :)
