### ISSUE TITLE
Top right fab buttons focus problem

### ISSUE THREAD

**Issue by ThibaultNocchi** [jellyfin/jellyfin-vue#553]
The fab buttons (dark mode and language) both have the same focus problem we had with the (now removed) fab buttons of the audio player (@ferferga). Maybe we should apply the same fix?

**Comment by Camc314** [comment]
What did we do to fix in the audio player?

**Comment by ThibaultNocchi** [comment]
Applied weird CSS classes ^^

**Comment by ThibaultNocchi** [comment]
https://github.com/jellyfin/jellyfin-vue/blob/55f58f675e1153637e0573f794d70e780ede52ba/components/Layout/AudioControls.vue#L301

**Comment by Camc314** [comment]
Ah

We might want to use:

https://github.com/vuetifyjs/vuetify/issues/8172#issuecomment-738304152

to enable hovering

**Comment by ThibaultNocchi** [comment]
Yup, might be worth a shot!
