### ISSUE TITLE
Document how to use Axe

### ISSUE THREAD

**Issue by ferferga** [jellyfin/jellyfin-vue#555]
Now that Axe is disabled by default, we should have some kind of documentation (probably in ``CONTRIBUTING.md``) in how to use it for users that are not frequent contributors here, so everyone's able to provide new features while keeping accessibility in mind.

**Comment by Camc314** [comment]
Or it could also go in the wiki?

**Comment by MrTimscampi** [comment]
Documentation is here: https://axe.vue-a11y.com/guide/api.html#run

To access it, it's the same as accessing Nuxt from the console: `$nuxt.$axe`
