### ISSUE TITLE
Album covers are not always centered in the full screen music UI

### ISSUE THREAD

**Issue by ferferga** [jellyfin/jellyfin-vue#558]
Perhaps this is an upstream issue.

**Comment by Camc314** [comment]
I don't think it is upstream:

![image](https://user-images.githubusercontent.com/18101008/104708178-43e5de80-5715-11eb-8441-c648f2f6fe02.png)

The element highlighted is the swiper slide which is centered.

**Comment by Camc314** [comment]
I've found a fix
