### ISSUE TITLE
Language selector shows only "Bokmål", not "Norsk" or "Norsk Bokmål"

### ISSUE THREAD

**Issue by hawken93** [jellyfin/jellyfin-vue#559]
"Bokmål" is a form of Norwegian but I think it's incorrect to show it without "Norsk bokmål" or some variant that starts with the main language.

Wikipedia for reference:
http://puu.sh/H70qY/e369f3cf47.png

Vue:
http://puu.sh/H70rz/499dd97a04.png

For ease of copying
```
Norsk bokmål
Norsk nynorsk
```

~Other alternatives~ doesn't sort well
```
Norsk
Nynorsk
```

**Comment by hawken93** [comment]
@oddstr13

**Comment by oddstr13** [comment]
Agree on `Norsk bokmål` and `Norsk nynorsk` if we're going to translate both, otherwise just `Norsk` for bokmål.

May be worth considering at least Sámi too, but I can't help translating that. https://en.wikipedia.org/wiki/S%C3%A1mi_languages#Norway

**Comment by AlfHou** [comment]
I fixed this in pull request #567

There is no Nynorsk translations in jellyfin-web that I can see. And my grades from Nynorsk in high school indicates that I should probably not attempt to translate to Nynorsk either 😛
