### ISSUE TITLE
Unable to fullscreen

### ISSUE THREAD

**Issue by AlfHou** [jellyfin/jellyfin-vue#570]
I am unable to fullscreen the media player. The cursor does not change when hovering

Tested on both firefox and chrome. Running master on both server and vue-client

![image](https://user-images.githubusercontent.com/20001253/104765157-bc29bf80-5768-11eb-8ef8-160d9265a43e.png)

**Comment by Camc314** [comment]
This feature has not been implemented yet.

Airplay, settings, captions, PiP, and Chromecast controls are not yet implemented

**Comment by AlfHou** [comment]
This is about regular fullscreen, it worked a couple of weeks ago. But if this is considered a non-implemented feature, then this issue can probably be closed.

**Comment by ferferga** [comment]
This could be reopened though to keep the track of the reimplementation
