### ISSUE TITLE
What are the names of the directories that the docker version saves to?

### ISSUE THREAD

**Issue by Darkwolf1515** [jellyfin/jellyfin-vue#584]
Would like to be able to configure where the folders are stored, normal Jellyfin used /config /media /cache as noted here. https://jellyfin.org/docs/general/administration/installing.html#docker

Just wondering what this uses, and if it can be documented. (Although I suppose this will all be irrelevant once merged with core.)

**Comment by MrTimscampi** [comment]
The docker container for the Vue client contains only the Vue client itself. You'll need a separate container for Jellyfin itself.

Currently, this client doesn't store anything, so there's no need to mount any volume.

**Comment by Darkwolf1515** [comment]
> 
> 
> The docker container for the Vue client contains only the Vue client itself. You'll need a separate container for Jellyfin itself.
Oh I know, i've been using it since the container first released.

> 
> Currently, this client doesn't store anything, so there's no need to mount any volume.
Gotcha, thanks!
