### ISSUE TITLE
Implement a virtual scroller for the library views

### ISSUE THREAD

**Issue by MrTimscampi** [jellyfin/jellyfin-vue#59]
Currently, the library view loads every item, resulting in a very large DOM and really bad performance from the client.

We should only render (and maybe load) what is visible to the user.

~~Using a component like [vue-virtual-scroller](https://github.com/Akryum/vue-virtual-scroller/) (Developed by a member of the core Vue.js team), would be the preferred solution to this.~~ After some tries on my end, this doesn't seem to work. Here's a Google implementation of what we want, for ideas: https://github.com/GoogleChromeLabs/ui-element-samples/blob/gh-pages/infinite-scroller/scripts/infinite-scroll.js

**Comment by ghenry22** [comment]
you could take a look at Ionic Framework for Vue.  It has a virtual scrolling component that deals with this quite well.  I use it for large music libraries in a subsonic client.

**Comment by MrTimscampi** [comment]
Fixed by #119
