### ISSUE TITLE
Artist page doesn't show albums

### ISSUE THREAD

**Issue by Extarys** [jellyfin/jellyfin-vue#637]
I only found #416 that was related to this. Maybe it's discussed in a "mega-issue" but I didn't see it.

I cloned the repo and tested right away.

Artist name, album and bio is loaded ok with `https://domain/Users/cd3eef25704645a39f561e25407a57ae/Items/0d33aa9c552f8205f9598b35760a3782`

The requested url for the albums (I assume) is right after:
```
https://domain/Items?userId=cd3eef25704645a39f561e25407a57ae&sortOrder=Descending&parentId=0d33aa9c552f8205f9598b35760a3782&sortBy=PremiereDate%2CProductionYear%2CSortName
```

Response is : 200: `{"Items":[],"TotalRecordCount":0,"StartIndex":0}`

![image](https://user-images.githubusercontent.com/11581433/106375165-dca46d00-6357-11eb-981d-d7aed1e06afe.png)

Using Jellyfin-web, I get 10 albums.

I didn't see any logs related to this on the server.

**Comment by Camc314** [comment]
> ```
> https://domain/Items?userId=cd3eef25704645a39f561e25407a57ae&sortOrder=Descending&parentId=0d33aa9c552f8205f9598b35760a3782&sortBy=PremiereDate%2CProductionYear%2CSortName
> ```

That's the right url.

What url is jf-web requesting when getting artist's albums?

**Comment by Extarys** [comment]
```
https://domain/Users/cd3eef25704645a39f561e25407a57ae/Items?SortOrder=Descending&IncludeItemTypes=MusicAlbum&Recursive=true&Fields=AudioInfo%2CParentId%2CPrimaryImageAspectRatio%2CBasicSyncInfo%2CAudioInfo%2CParentId%2CPrimaryImageAspectRatio%2CBasicSyncInfo&Limit=100&StartIndex=0&CollapseBoxSetItems=false&AlbumArtistIds=0d33aa9c552f8205f9598b35760a3782&SortBy=PremiereDate%2CProductionYear%2CSortname
```
(Same artist, from jf-web)

I think the jf-vue request miss the `&IncludeItemTypes=MusicAlbum` parameter.

Thank you very much for your PR.

**Comment by Camc314** [comment]
> Thank you very much for your PR.

No worries 😉
