### ISSUE TITLE
Back button now goes back a whole webpage

### ISSUE THREAD

**Issue by Darkwolf1515** [jellyfin/jellyfin-vue#677]
Clicking the back arrow will send you back a full webpage, not to the last server url, but the last website you were on before.

**Comment by ferferga** [comment]
@Darkwolf1515 Is this right after logging it if I understood correctly, right?

As soon as the login process complete, we erase the history so there's no way to go back to login page aside from logging out

**Comment by Darkwolf1515** [comment]
It's how it started, but I played a couple songs and it still triggered, might just be the start up however. Should probably make a separate issue for the new crashing and having to delete cookies to get back in however.

**Comment by ThibaultNocchi** [comment]
@Darkwolf1515 Do you have a reproducible example of this? :)
