### ISSUE TITLE
Loading the website when logged and the server down doesn't redirect

### ISSUE THREAD

**Issue by ThibaultNocchi** [jellyfin/jellyfin-vue#707]
**Describe The Bug**
If you are logged in and the server is down, refreshing the page just shows you bugged home page (even though the URL was changed to /selectserver)
![print_screen_2021-02-11-16-12-48](https://user-images.githubusercontent.com/1619359/107655890-0036b400-6c84-11eb-9daf-06935bb70759.png)

**Steps To Reproduce**
- Log in and "remember me"
- Stop the JF server of the logged user
- Load the page, admire the bug

**Comment by Camc314** [comment]
I don't there is anything we can do about this, maybe set a timeout on the network request for the server?

**Comment by ThibaultNocchi** [comment]
I should look into this more, cause I'm sure there's something in the process which might be wrong

**Comment by Camc314** [comment]
If I remember correctly, it calls /me, and because there is no connection, it is just `pending` infinitely, and therefore never redirects
