### ISSUE TITLE
Can't click on the artists on the music library page

### ISSUE THREAD

**Issue by ThibaultNocchi** [jellyfin/jellyfin-vue#835]
**Describe The Bug**

On the music library page, it'd be great to be able to click on the artist to directly be redirected to their page.

![print_screen_2021-03-04-19-51-36](https://user-images.githubusercontent.com/1619359/110014408-0e2ba200-7d23-11eb-9a06-0a930ec0d98d.png)

Here I'd love to click on "C2C" to go to the group page, instead of currently being redirected to the "Tetra" page.

**Comment by neopc10** [comment]
Tangentially related to this, I'd like to be able to click the artist name/logo on the home screen "recently added" banner and be redirected to their page.

**Comment by ThibaultNocchi** [comment]
Well, it's using the same component so it should work everywhere :p

**Comment by MrTimscampi** [comment]
> Well, it's using the same component so it should work everywhere :p

The artist name/logo on the home header is a completely different component, though :yum:
