### ISSUE TITLE
[tweak] Album Details and Edit Metadata

### ISSUE THREAD

**Issue by neopc10** [jellyfin/jellyfin-vue#839]
I'll bet that this is merely an oversight but Jellyfin does retrieve album descriptions/"overviews" but they are not yet given a spot on the album details page like they are on TV or Movie pages.

Furthermore, this has more to do with the "edit metadata" window being generic but the user likely should not be allowed to change the tagline of a music album.

edit: the "edit metadata" button for each track in album view leads to the metadata for the album and not the individual track.

**Comment by ferferga** [comment]
What are the silly things that happens when shuffling?

**Comment by neopc10** [comment]
![image](https://user-images.githubusercontent.com/1365322/110177127-75ecf600-7dd2-11eb-8cfd-cbdc187920f8.png)

**Comment by ferferga** [comment]
@neopc10 That error indicates an issue in your build. You either stopped nuxt or something is borked in your build environment

**Comment by neopc10** [comment]
It was a docker container from two days ago but the most recent one works just fine!
