### ISSUE TITLE
Latest Media is limited...

### ISSUE THREAD

**Issue by neopc10** [jellyfin/jellyfin-vue#865]
...by number of TV episodes or tracks rather than by number of TV shows or albums. Anecdotally, jf-web seems to have the same caps and the ATV is slightly more lenient. Dramatically increasing the cap (episodes, tracks) or showing the most recent ~12 unwatched (if set) shows or albums regardless of the number of items in each would be appreciated if possible.

![image](https://user-images.githubusercontent.com/1365322/110648806-09ce1180-8187-11eb-9f07-897934329feb.png)

**Comment by ThibaultNocchi** [comment]
That's a server side problem indeed. I think the limit we set refers to the number of *episodes*. So the more episodes you have by show, the less shows you'll see on these sliders.

**Comment by MrTimscampi** [comment]
This is a known bug from the server. There's no proper fix we can do on our side.
