### ISSUE TITLE
Branding text doesn't get reset when changing between servers

### ISSUE THREAD

**Issue by MrTimscampi** [jellyfin/jellyfin-vue#906]
**Describe The Bug**

When connecting to a server with branding text (Like the demo server) and switching to another server without branding, the branding is never reset, leading to the wrong branding shown.

**Steps To Reproduce**

1. Connect to `demo.jellyfin.org`
2. Switch servers to a server without branding

**Expected Behavior**

The branding should be reset properly when switching servers.

**Comment by jakobkukla** [comment]
I can't reproduce this. Getting expected behaviour with both Chrome and Firefox. (You mean the branding text with the login info and copyright notice, right?)

**Comment by ThibaultNocchi** [comment]
Same here, it seems to be an issue with the cloudflare hosted version only.

**Comment by MrTimscampi** [comment]
It seems like this may be a Cloudflare issue only. I'm trying a different way to build the Cloudflare deployment and I'll close this if it fixes it.
