### ISSUE TITLE
UI crashes on page reloads

### ISSUE THREAD

**Issue by lyarenei** [jellyfin/jellyfin-vue#914]
**Describe The Bug**
The UI crashes when reloading specific pages. The only reload which works correctly is when on homepage.

Reloading the page while browsing the library results in `empty library` message.
All libraries on the left panel are gone. Clicking on Home or my username doesn't do anything. Same for the theme button. The only recovery from this state is to reload the whole app via server URL (hit enter in URL bar).

Reloading the page while on album details results in `HTTP 500 error` logged in console. Going back doesn't help, only reload via server URL as described above helps. The URL must be for the server, without`/musicalbum/id`. This applies to TV shows and movies as well (with their own respective URL paths).

Reloading page on settings results in similar state as library, but the error in console is different.

**Steps To Reproduce**

For library
1. Log in to jellyfin.
2. Go to your library of choice
3. Reload the page in browser
4. Library is shown as empty and UI elements don't work

For album/tv show/movie
1. Log in to jellyfin.
2. Go to your library of choice
3. Open a library item of your choice
3. Reload the page in browser
4. Error page is displayed

**Expected Behavior**
Everything reloads properly, like on a homepage. UI elements works as expected.

**Logs**
Shown in the screenshots below

**Screenshots**
Library after reload
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/26324629/112297663-76bccd80-8c96-11eb-9708-2587994c5870.png">

Album after reload
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/26324629/112297841-a53aa880-8c96-11eb-874b-ecb3dca08ea9.png">

Settings page after reload
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/26324629/112300874-a02b2880-8c99-11eb-990a-b1a11ec78afe.png">

**System (please complete the following information):**

- Platform: macOS 11
- Browser: Safari, Firefox
- Jellyfin Version:
    - server: latest nightly from docker hub
    - vue client:`unstable-ssr.2021-03-24.a9150ef`

**Additional Context**
Safari was tested with all addons disabled.
Firefox was tested with my usual set of addons enabled.

**Comment by ThibaultNocchi** [comment]
Hey, thanks for the report, I can confirm this

**Comment by ThibaultNocchi** [comment]
I haven't tried but it should be fixed by #926, gonna try later

**Comment by lyarenei** [comment]
@ferferga 
Sorry, I didn't notice any updates on this.

I quickly tested the `ssr.2021-04-07.e3359b9` release.
Reload of a library - works
Reload of an album - works
Reload of a movie - works
Reload of a tv show episode - works
Reload of settings - still breaks as described
Reload of a TV show - error page is not displayed anymore, but episode list disappears for that particular show until the app is reloaded via URL. No errors in browser console are logged.

**Comment by ThibaultNocchi** [comment]
I confirm this

**Comment by ferferga** [comment]
Fixed by #1632
