### ISSUE TITLE
Cannot select a specific song from an album

### ISSUE THREAD

**Issue by Darkwolf1515** [jellyfin/jellyfin-vue#976]
**Describe The Bug**

Seletcing a song from an album just plays the first one, and kicks me out of the album.

**Steps To Reproduce**

1. Open an album, and select a song thats not 1
2. See that it plays the first track, and youre now back in album view.

**Expected Behavior**
To play the song I chose and not kick me out.

**System (please complete the following information):**

- Platform: Docker
- Browser: Brave
- Jellyfin Version: 1.70 stable.

**Comment by ferferga** [comment]
Could reproduce:

**Complete steps to reproduce:**

* Play something and open fullscreen music player.
* Exit fullscreen music player.
* Switch to last item in queue.
* Change the album or start a completely new queue (so player goes from playing - stopped - playing) state

[This watcher will be triggered](https://github.com/jellyfin/jellyfin-vue/blob/master/client/pages/fullscreen/playback/index.vue#L83), even when the component is not active it seems.

No clue why honestly, there's still something about keepalives we're missing maybe?
