### ISSUE TITLE
toggle buttons on the header keep their elevation on scroll

### ISSUE THREAD

**Issue by dkanada** [jellyfin/jellyfin-vue#997]
If you open a random page and scroll down, the toggle buttons previously lost their elevation, but now they keep it. This gives the header an odd look.

**Comment by dkanada** [comment]
I originally noticed this on music libraries because they are often missing backdrops, but any page without a backdrop that expects one will leave the FAB property enabled on the header buttons. A proper fix would be automating the backdrop + header updates with some kind of mixin, and only setting FAB when a backdrop successfully loads. I'll include an example of the offending code below.

```
  watch: {
    item: {
      handler(val: BaseItemDto): void {
        this.setPageTitle({ title: val.Name });

        const hash = this.getBlurhash(val, ImageType.Backdrop);

        this.setBackdrop({ hash });
      },
      immediate: true,
      deep: true
    }
  },
  activated() {
    this.setAppBarOpacity({ opaqueAppBar: false });
  },
  deactivated() {
    this.setAppBarOpacity({ opaqueAppBar: true });
    this.clearBackdrop();
  }
```

**Comment by ferferga** [comment]
#1593 fixes this

**Comment by ferferga** [comment]
#1593 was merged
